name: CI/CD Pipeline

on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies and run tests
        run: |
          pip install -r requirements.txt
          PYTHONPATH=. pytest tests/

      - name: Build Docker image
        run: docker build -t ci-cd:latest .

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: Push to Docker Hub (Staging)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ci-cd:latest ${{ secrets.DOCKER_HUB_USER }}/ci-cd:staging
          docker push ${{ secrets.DOCKER_HUB_USER }}/ci-cd:staging
